---
  - name: Playbook
    hosts: matteo
    become: yes
    become_user: root
    tasks:
      - name: apt-get update
        apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
      - name: apt-get upgrade
        apt: upgrade=dist force_apt_get=yes
      - name: Install nginx packages
        apt:
          pkg:
            - nginx
            - psmisc
            - vim
            - net-tools
            - git
            - uuid
      - name: Copia File di test da local a Remote
        ansible.builtin.copy:
          src: ./testfile.txt       # Jenkins
          dest: /root/testfile.txt  # Server Host
      - name: shell execute tests
        ansible.builtin.command:
          argv:
            - ls
            - /var/log
            - -R
        register: lsOutput
      - name: copy output to file
        copy:
          content: "{{ lsOutput.stdout }}"
          dest: /root/ciccio.txt
      - name: Fetch risultati
        ansible.builtin.fetch:
          src: /root/ciccio.txt     # Fetch filed from Remote
          dest: ciccio.txt    # Copy files to Local (Jenkins)
          flat: yes
      - name: shell
        become: no
        local_action:
          module: ansible.builtin.command
          argv:
            - cat
            - ciccio.txt
            