---
  - name: Playbook
    hosts: all
    become: yes
    become_user: root
    tasks:
      - name: apt-get update
        apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
      - name: apt-get upgrade
        apt: upgrade=dist force_apt_get=yes
      - name: Install nginx packages
        apt:
          pkg:
            - nginx
            - psmisc
            - vim
            - net-tools
            - git
            - uuid
      - name: Copia File di test da local a Remote
        ansible.builtin.copy:
          src: ./testfile.txt       # Jenkins
          dest: /root/testfile.txt  # Server Host
      - name: shell execute tests
        ansible.builtin.shell:
          cmd: ls -R >> /root/ciccio.txt
          chdir: /var/log/
      - name: Fetch risultati
        ansible.builtin.fetch:
          src: /root/ciccio.txt     # Fetch filed from Remote
          dest: /root/ciccio.txt    # Copy files to Local (Jenkins)
      - name: shell
        local_action:
          ansible.builtin.shell:
          cmd: cat /root/ciccio.txt

      
